FROM        amazoncorretto:24

LABEL       maintainer="@yunuservices"

RUN         yum update \
            && yum -y install --no-install-recommends curl ca-certificates openssl git tar sqlite3 fontconfig tzdata locales iproute2 \
            && yum clean all \
            && rm -rf /var/cache/yum \
            && useradd -m -d /home/container container \
            && locale-gen en_US.UTF-8

RUN         curl -sSL https://github.com/OpticFusion1/MCAntiMalware/releases/latest/download/MCAntiMalware.jar \
            -o /MCAntiMalware.jar

ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../../entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]