FROM        registry.access.redhat.com/ubi9/openjdk-21

LABEL maintainer="@yunuservices"

ENV         DEBIAN_FRONTEND noninteractive

USER root
RUN mkdir -p /var/cache/yum && chmod -R 0777 /var/cache/yum

RUN         microdnf update \
            && microdnf -y install --no-install-recommends curl ffmpeg iproute2 git sqlite3 python3 tzdata ca-certificates dnsutils fontconfig libfreetype6 libstdc++6 lsof build-essential locales \
            && microdnf clean \
            && rm -rf /var/lib/apt/lists/* \
            && useradd -m -d /home/container container \
            && locale-gen en_US.UTF-8

ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../../entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]