FROM        amazoncorretto:21

LABEL       maintainer="@yunuservices"

RUN         yum update \
            && yum -y install curl ca-certificates openssl git tar sqlite fontconfig tzdata \
            && yum clean all \
            && rm -rf /var/cache/yum \
            && useradd -m -d /home/container container

RUN         curl -sSL https://github.com/OpticFusion1/MCAntiMalware/releases/latest/download/MCAntiMalware.jar \
            -o /MCAntiMalware.jar

ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../../entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]