name: Build GraalVM

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 1 *"
  push:
    branches: [ "main" ]
    paths:
      - ./graalvm/**

jobs:
  java:
    name: "java:${{ matrix.tag.name }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        tag:
          - { version: "25", path: "./graalvm/jdk", name: "gvm-jdk_25" }
          - { version: "24", path: "./graalvm/jdk", name: "gvm-jdk_24" }
          - { version: "21", path: "./graalvm/jdk", name: "gvm-jdk_21" }
          - { version: "25.0.0", path: "./graalvm/ce", name: "gvm-ce_25.0.0" }
          - { version: "24.0.2", path: "./graalvm/ce", name: "gvm-ce_24.0.2" }
          - { version: "21.0.2", path: "./graalvm/ce", name: "gvm-ce_21.0.2" }
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        if: github.event_name != 'pull_request'
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/login-action@v2
        with:
          registry: container-registry.oracle.com
          username: ${{ secrets.ORACLE_SSO_USERNAME }}
          password: ${{ secrets.ORACLE_SSO_PASSWORD }}
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/yunuservices/java
          tags: |
            type=raw,${{ matrix.tag.name }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.tag.path }}/${{ matrix.tag.version }}/dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_graalvm.outputs.tags }}
          labels: ${{ steps.meta_graalvm.outputs.labels }}